export const ENK = {
  root: "/",
  home: "/home",
  about: "/about",
  journey: "/journey",
  skill: "/skill",
  experience: "/experience",
  project: "/project",
  caseStudy: "/case-study",
  research: "/research",
  service: "/service",
  tool: "/tool",
  achievement: "/achievement",
  testimonial: "/testimonial",
  talk: "/talks-event",
  blog: "/blog",
  media: "/media",
  gallery: "/gallery",
  education: "/education",
  hobbies: "/hobbies",
  volunteering: "/volunteering",
  social: "/social-profile",
  faqs: "/faqs",
  contact: "/contact",
  resume: "/resume",
};
