import {
  techAngularIcon,
  techAuth0Icon,
  techAwsAmplifyIcon,
  techAwsIcon,
  techBootstrapIcon,
  techChakraUIIcon,
  techCloudnaryIcon,
  techContentfulIcon,
  techCppIcon,
  techCssIcon,
  techDynamoDBIcon,
  techFastlaneIcon,
  techFirebaseIcon,
  techFirebaseStogrageIcon,
  techFlutterIcon,
  techGoLangIcon,
  techGoogleAnalyticIcon,
  techGraphQlIcon,
  techGrpcIcon,
  techHarushaIcon,
  techHotjarIcon,
  techHtmlIcon,
  techJavaIcon,
  techJsIcon,
  techKotlinIcon,
  techMaterialUIIcon,
  techMixpanelIcon,
  techMongoDBIcon,
  techMySqlIcon,
  techNativeScriptIcon,
  techNeo4jIcon,
  techNextIcon,
  techNodeIcon,
  techOktaIcon,
  techPayPalIcon,
  techPostHogIcon,
  techPrettierIcon,
  techPstgreSqlIcon,
  techPwaIcon,
  techPythonIcon,
  techRazorPayIcon,
  techReactIcon,
  techRecoilIcon,
  techRedisIcon,
  techReduxIcon,
  techSanityIcon,
  techStyledComponentIcon,
  techSuperBase,
  techSwiftIcon,
  techTailwindIcon,
  techViteIcon,
  techVueIcon,
  techWordPressIcon,
  techWorkboxIcon,
} from "./brandIcons";
import { SERVICE_TECH_STACK_ICONS } from "./serviceTechStack";

export const TECH_ICONS = {
  [SERVICE_TECH_STACK_ICONS.REACT]: techReactIcon,
  [SERVICE_TECH_STACK_ICONS.VUE]: techVueIcon,
  [SERVICE_TECH_STACK_ICONS.ANGULAR]: techAngularIcon,
  [SERVICE_TECH_STACK_ICONS.TAILWIND]: techTailwindIcon,
  [SERVICE_TECH_STACK_ICONS.BOOTSTRAP]: techBootstrapIcon,
  [SERVICE_TECH_STACK_ICONS.MATERIALUI]: techMaterialUIIcon,
  [SERVICE_TECH_STACK_ICONS.CHAKRAUI]: techChakraUIIcon,
  [SERVICE_TECH_STACK_ICONS.STYLEDCOMPONENT]: techStyledComponentIcon,
  [SERVICE_TECH_STACK_ICONS.CSS]: techCssIcon,
  [SERVICE_TECH_STACK_ICONS.HTML]: techHtmlIcon,
  [SERVICE_TECH_STACK_ICONS.NEXT]: techNextIcon,
  [SERVICE_TECH_STACK_ICONS.JAVASCRIPT]: techJsIcon,
  [SERVICE_TECH_STACK_ICONS.VITE]: techViteIcon,
  [SERVICE_TECH_STACK_ICONS.PRETTIER]: techPrettierIcon,
  [SERVICE_TECH_STACK_ICONS.SANITY]: techSanityIcon,
  [SERVICE_TECH_STACK_ICONS.CONTENTFUL]: techContentfulIcon,
  [SERVICE_TECH_STACK_ICONS.WORDPRESS]: techWordPressIcon,
  [SERVICE_TECH_STACK_ICONS.FLUTTER]: techFlutterIcon,
  [SERVICE_TECH_STACK_ICONS.NATIVESCRIPT]: techNativeScriptIcon,
  [SERVICE_TECH_STACK_ICONS.KOTLIN]: techKotlinIcon,
  [SERVICE_TECH_STACK_ICONS.SWIFT]: techSwiftIcon,
  [SERVICE_TECH_STACK_ICONS.JAVA]: techJavaIcon,
  [SERVICE_TECH_STACK_ICONS.WORKBOX]: techWorkboxIcon,
  [SERVICE_TECH_STACK_ICONS.PWA]: techPwaIcon,
  [SERVICE_TECH_STACK_ICONS.FIREBASE]: techFirebaseIcon,
  [SERVICE_TECH_STACK_ICONS.FASTLANE]: techFastlaneIcon,
  [SERVICE_TECH_STACK_ICONS.NODE]: techNodeIcon,
  [SERVICE_TECH_STACK_ICONS.PYTHON]: techPythonIcon,
  [SERVICE_TECH_STACK_ICONS.GOLANG]: techGoLangIcon,
  [SERVICE_TECH_STACK_ICONS.CPP]: techCppIcon,
  [SERVICE_TECH_STACK_ICONS.POSTGRESQL]: techPstgreSqlIcon,
  [SERVICE_TECH_STACK_ICONS.MYSQL]: techMySqlIcon,
  [SERVICE_TECH_STACK_ICONS.MONGODB]: techMongoDBIcon,
  [SERVICE_TECH_STACK_ICONS.DYNAMODB]: techDynamoDBIcon,
  [SERVICE_TECH_STACK_ICONS.NEO4J]: techNeo4jIcon,
  [SERVICE_TECH_STACK_ICONS.AUTH0]: techAuth0Icon,
  [SERVICE_TECH_STACK_ICONS.OKTA]: techOktaIcon,
  [SERVICE_TECH_STACK_ICONS.GRAPHQL]: techGraphQlIcon,
  [SERVICE_TECH_STACK_ICONS.GRPC]: techGrpcIcon,
  [SERVICE_TECH_STACK_ICONS.AWS]: techAwsIcon,
  [SERVICE_TECH_STACK_ICONS.CLOUDINARY]: techCloudnaryIcon,
  [SERVICE_TECH_STACK_ICONS.FIREBASESTORAGE]: techFirebaseStogrageIcon,
  [SERVICE_TECH_STACK_ICONS.REDUX]: techReduxIcon,
  [SERVICE_TECH_STACK_ICONS.RECOIL]: techRecoilIcon,
  [SERVICE_TECH_STACK_ICONS.REDIS]: techRedisIcon,
  [SERVICE_TECH_STACK_ICONS.HARUSHA]: techHarushaIcon,
  [SERVICE_TECH_STACK_ICONS.SUPABASE]: techSuperBase,
  [SERVICE_TECH_STACK_ICONS.AWS_AMPLIFY]: techAwsAmplifyIcon,
  [SERVICE_TECH_STACK_ICONS.PAYPAL]: techPayPalIcon,
  [SERVICE_TECH_STACK_ICONS.RAZORPAY]: techRazorPayIcon,
  [SERVICE_TECH_STACK_ICONS.GOOGLE_ANALYTICS]: techGoogleAnalyticIcon,
  [SERVICE_TECH_STACK_ICONS.HOTJAR]: techHotjarIcon,
  [SERVICE_TECH_STACK_ICONS.MIXPANEL]: techMixpanelIcon,
  [SERVICE_TECH_STACK_ICONS.POSTHOG]: techPostHogIcon,
};
