export const skillsFoundation = {
  group: "Foundations of Computation & Programming",
  list: [
    {
      name: "C Programming",
      version: "strong",
      status: "core",
      tagline:
        "Procedural programming with explicit control over memory and execution",
      highlights: [
        "Memory layout, pointers, and manual allocation strategies",
        "Control flow and data modeling using structs and functions",
        "Implementing classic data structures from scratch",
        "Understanding stack vs heap behavior",
        "Interfacing with operating system primitives",
        "Writing performance-aware and predictable code",
        "Debugging using low-level reasoning",
        "Bridging hardware concepts with software behavior",
      ],
    },
    {
      name: "C++ Programming",
      version: "advanced",
      status: "core",
      tagline:
        "Systems-oriented and object-oriented programming with performance awareness",
      highlights: [
        "Object-oriented modeling and abstraction design",
        "Resource management using RAII principles",
        "STL containers, algorithms, and iterators",
        "Custom data structures and performance tradeoffs",
        "Compile-time vs runtime design decisions",
        "Bridging low-level control with high-level abstractions",
        "Understanding object lifetimes and memory ownership",
        "Building reusable and extensible system components",
      ],
    },
    {
      name: "Data Structures & Algorithms",
      version: "advanced",
      status: "core",
      tagline: "Designing efficient solutions using algorithmic thinking",
      highlights: [
        "Linear and non-linear data structures",
        "Algorithmic complexity analysis (time and space)",
        "Problem decomposition and abstraction",
        "Recursive and iterative design patterns",
        "Greedy, divide-and-conquer, and dynamic programming",
        "Tradeoffs between simplicity and performance",
        "Implementing algorithms in C/C++",
        "Applying DSA concepts to real-world systems",
      ],
    },
    {
      name: "Theory of Computation",
      version: "foundational",
      status: "background",
      tagline: "Formal reasoning about what can be computed and how",
      highlights: [
        "Models of computation and formal languages",
        "Finite automata and regular languages",
        "Context-free grammars and pushdown automata",
        "Turing machines and computability limits",
        "Decidability and undecidability concepts",
        "Reducibility and problem classification",
        "Relationship between computation and complexity",
        "Using theory to reason about system limits",
      ],
    },
    {
      name: "Compiler Design",
      version: "foundational",
      status: "background",
      tagline:
        "Understanding how high-level programs are translated into executable form",
      highlights: [
        "Lexical analysis and tokenization",
        "Syntax analysis using grammars and parsers",
        "Abstract syntax trees and semantic analysis",
        "Symbol tables and scope resolution",
        "Intermediate representations",
        "Basic code generation concepts",
        "Error handling during compilation",
        "How language design affects performance and safety",
      ],
    },
    {
      name: "JavaScript",
      version: "advanced",
      status: "core",
      tagline: "Primary language for backend and platform development",
      highlights: [
        "Language fundamentals and runtime behavior",
        "Asynchronous programming and event-driven models",
        "Closures, scopes, and execution contexts",
        "Error handling and promise-based workflows",
        "Modular code organization",
        "Using JavaScript for scalable backend systems",
        "Interfacing with databases and services",
        "Writing maintainable production-grade code",
        "Understanding performance characteristics",
      ],
    },
    {
      name: "Java",
      version: "working",
      status: "background",
      tagline:
        "Strongly-typed, object-oriented programming for structured systems",
      highlights: [
        "Core object-oriented programming concepts",
        "Class design and inheritance hierarchies",
        "Exception handling and type safety",
        "Standard library usage",
        "Understanding JVM execution model",
        "Basic concurrency concepts",
        "Applying design patterns in Java",
        "Comparing Java abstractions with C++ and JS",
      ],
    },
    {
      name: "Python",
      version: "working",
      status: "active",
      tagline: "High-level scripting and tooling for data and automation",
      highlights: [
        "Language fundamentals and idiomatic usage",
        "Scripting and rapid prototyping",
        "Using Python for data processing",
        "Working with numerical and scientific libraries",
        "Automation and tooling support",
        "Bridging Python with ML workflows",
        "Readable and expressive code design",
        "Using Python as a glue language",
      ],
    },
  ],
};
