export const skillsSoftwareArch = {
  group: "Software Architecture & Engineering",
  list: [
    {
      name: "Software Engineering",
      version: "advanced",
      status: "core",
      tagline: "Structured development of maintainable software systems",
      highlights: [
        "Requirement analysis and system scoping",
        "Translating requirements into technical designs",
        "Version control and collaboration workflows",
        "Testing strategies and quality assurance",
        "Documentation and knowledge transfer",
        "Managing technical debt intentionally",
        "Balancing speed and maintainability",
        "Engineering tradeoff analysis",
      ],
    },
    {
      name: "Software Architecture",
      version: "strong",
      status: "core",
      tagline: "Designing systems that scale and evolve",
      highlights: [
        "Layered and modular architectures",
        "Separation of concerns and boundaries",
        "Designing for extensibility and change",
        "Service decomposition and integration",
        "Data flow and dependency management",
        "Choosing architectures based on constraints",
        "Avoiding over-engineering",
        "Long-term system evolution planning",
      ],
    },
    {
      name: "Object-Oriented Design",
      version: "strong",
      status: "active",
      tagline: "Modeling systems using objects and responsibilities",
      highlights: [
        "SOLID principles in practice",
        "Design patterns and their tradeoffs",
        "UML diagrams for communication",
        "Encapsulation and abstraction boundaries",
        "Reducing coupling and increasing cohesion",
        "Refactoring toward better design",
        "Designing for testability",
        "Mapping domain concepts to code",
      ],
    },
    {
      name: "Software Project Management",
      version: "working",
      status: "active",
      tagline:
        "Planning, coordinating, and executing software projects with engineering constraints in mind",
      highlights: [
        "Translating product goals into technical tasks",
        "Breaking down systems into deliverable milestones",
        "Estimating effort using technical understanding",
        "Managing scope, tradeoffs, and constraints",
        "Coordinating development workflows",
        "Balancing speed, quality, and technical debt",
        "Tracking progress and adapting plans",
        "Communicating risks and dependencies",
        "Delivering projects end-to-end",
      ],
    },
  ],
};
