export const skillsSystemOs = {
  group: "Systems, OS & Infrastructure",
  list: [
    {
      name: "Operating Systems",
      version: "working",
      status: "background",
      tagline: "Understanding how programs execute and interact with hardware",
      highlights: [
        "Process and thread lifecycle concepts",
        "Scheduling and context switching basics",
        "Virtual memory and address spaces",
        "File systems and I/O models",
        "User vs kernel space separation",
        "Concurrency fundamentals and pitfalls",
        "How OS behavior affects application design",
        "Reasoning about performance and resource limits",
      ],
    },
    {
      name: "Linux Systems",
      version: "working",
      status: "active",
      tagline: "Using Linux as a development and deployment environment",
      highlights: [
        "Command-line proficiency and shell usage",
        "Process inspection and management",
        "Filesystem hierarchy and permissions",
        "Environment configuration for applications",
        "Basic system troubleshooting",
        "Service management for deployed apps",
        "Understanding logs and runtime behavior",
        "Using Linux as a production platform",
      ],
    },
    {
      name: "Computer Networks",
      version: "foundational",
      status: "background",
      tagline: "Networking concepts that support distributed systems",
      highlights: [
        "Client–server communication model",
        "TCP/IP fundamentals",
        "HTTP request–response lifecycle",
        "DNS and routing basics",
        "Latency, throughput, and reliability concepts",
        "Connection handling in backend systems",
        "How networks fail and recover",
        "Designing APIs with network constraints in mind",
      ],
    },
    {
      name: "Server Infrastructure",
      version: "strong",
      status: "active",
      tagline: "Deploying, running, and maintaining production backend systems",
      highlights: [
        "Provisioning and managing VPS-based servers",
        "Configuring web servers and reverse proxies",
        "Process management and application lifecycle control",
        "Environment configuration and secrets handling",
        "Deploying Node.js applications to production",
        "Handling logs, restarts, and basic monitoring",
        "Understanding infrastructure failure modes",
        "Balancing simplicity with reliability",
        "Designing infrastructure to support application needs",
      ],
    },
  ],
};
