export const skillsUI = {
  group: "UI Engineering & Application Interfaces",
  list: [
    {
      name: "React",
      version: "advanced",
      status: "core",
      tagline: "Component-driven UI development for complex applications",
      highlights: [
        "Component architecture and composition patterns",
        "State management and unidirectional data flow",
        "Hooks and lifecycle reasoning",
        "Handling side effects and async UI behavior",
        "Optimizing rendering and performance",
        "Designing reusable UI components",
        "Managing large-scale React codebases",
        "Integrating React with backend APIs",
        "Applying React patterns to real-world systems",
      ],
    },
    {
      name: "Next.js",
      version: "advanced",
      status: "core",
      tagline:
        "Full-stack React framework for production-grade web applications",
      highlights: [
        "File-based routing and application structure",
        "Server-side rendering and static generation",
        "Data fetching strategies and caching",
        "API routes and backend integration",
        "Handling authentication flows",
        "SEO and performance optimization",
        "Environment configuration and builds",
        "Deploying and scaling Next.js applications",
        "Using Next.js as a platform framework",
      ],
    },
    {
      name: "HTML & Modular CSS",
      version: "advanced",
      status: "core",
      tagline: "Semantic markup and scalable styling systems",
      highlights: [
        "Semantic HTML for structure and accessibility",
        "CSS Modules for scoped and maintainable styles",
        "Responsive and adaptive layout design",
        "Flexbox and Grid layout systems",
        "Managing design consistency across components",
        "Avoiding global style conflicts",
        "Performance-aware styling decisions",
        "Building maintainable UI style architectures",
      ],
    },
    {
      name: "React Native",
      version: "strong",
      status: "active",
      tagline: "Cross-platform mobile application development using React",
      highlights: [
        "Shared component logic across platforms",
        "Platform-specific UI considerations",
        "Navigation and screen management",
        "Handling mobile performance constraints",
        "Interacting with device capabilities",
        "Managing state and side effects in mobile apps",
        "Building maintainable mobile UI architectures",
        "Integrating mobile apps with backend services",
      ],
    },
    {
      name: "Electron.js",
      version: "working",
      status: "active",
      tagline: "Desktop application development using web technologies",
      highlights: [
        "Building cross-platform desktop applications",
        "Bridging frontend UI with system-level APIs",
        "Managing main and renderer processes",
        "Packaging and distributing desktop apps",
        "Handling filesystem and OS interactions",
        "Performance and security considerations",
        "Reusing web UI architectures for desktop",
        "Integrating desktop apps with backend services",
      ],
    },
  ],
};
